config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  post 'posts/index'
  get 'users/index'
  get '/search', to: 'users#search'
  
  
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/auth/:provider/callback' => 'users/sessions#create'
    # get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "posts#index"

  resources :users do
    post 'remove_avatar'
  end

  resources :posts do 
    resources :comments, only: [:new, :edit]
  end 

  resources :comments, only: [:create, :update, :destroy]
  
  resources :likes, only: [:create, :destroy]

  resources :friend_reqs, only: [:create, :show] do
    member do
      post 'accept'
      delete 'reject'
    end
  end
      
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user

    belongs_to :commentable, polymorphic: true #belongs to post

    has_many :comments, as: :commentable, dependent: :destroy

    has_many :likes, as: :likable, dependent: :destroy

    validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    # before_action :comment_params
    def new
        # @post = Post.find(params[:post_id])
    end

    def create
        # binding.pry
        @post = Post.find(params[:commentable_id])
        @comment = current_user.comments.build(comment_params)
        if @comment.save
            flash[:notice] = "You have commented"
            redirect_back fallback_location: post_path(@post)
        else
            flash[:alert] = "Cannot create comment"
        end
    end

    def edit 
        @post = Post.find(params[:post_id])
        render 'posts/show'
    end

    def destroy
        # @post = Post.find(params[:commentable_id])
        # @comment = @post.comments.find(params[:commentable_id])
        @comment = Comment.find(params[:comment_id])
        if @comment.destroy
            # redirect_back post_path(@post)
            flash[:notice] = "You have delete this comment."
            redirect_back fallback_location:current_user
        else 
            flash[:error] = "Comment cannot be deleted"
            redirect_back fallback_location:current_user
        end
    end

    def comment_params
        params.permit(:body, :commentable_type, :commentable_id)
      end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<div class='border '>

  <strong>
  <%=link_to comment.user.name, comment.user %>
  </strong>

  <%= comment.body %>
  <li> (<%=comment.likes.count%> Likes)</li>
  <div class="p-2" style="background-color: #eee;">
    <%like = comment.likes.where(user_id: current_user.id).first%>
    <%if like.nil?%>
    <%= button_to 'Like', likes_path, params: {like: {user_id: current_user.id, likable_id: comment.id, likable_type: 'Comment'}}, class: "btn-sm btn btn-outline-primary float-start"%>
    <%else%>
    <%=button_to 'Like', like_url(id_like: like.id, id:comment.user.id), method: :delete, class: "btn-sm btn btn-outline-primary float-start" %>
    <%end%>
    <%if comment.user == current_user %>
        <%=button_to 'Delete comment', comment_url(comment_id: comment.id, id: comment.user.id), method: :delete, class: "btn-sm btn btn-outline-primary float-right"%>
    <%end%>
  </div>
</div>
<br>

app/views/comments/_form.html.erb
<%= form_with url: '/comments',action: :create, method: :post do |form| %>
    <%# <%form.hidden_field :post_id, value: params[post_id]%> 
  <p>
    <%# <%= current_user.name%> 
  </p>
  <p>
    <%= form.text_area :body, placeholder: "Comment.." %>
  </p>
  <p>
    <%=form.hidden_field :commentable_type, value: type %>
    <%=form.hidden_field :commentable_id, value: id  %>
  </p>
  <p>
    <%= form.submit "Post this comment", class: "btn btn-dark"%>
  </p>
</p>
<% end %>