config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  post 'posts/index'
  get 'users/index'
  get '/search', to: 'users#search'
  
  
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/auth/:provider/callback' => 'users/sessions#create'
    # get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "posts#index"

  resources :users do
    post 'remove_avatar'
  end

  resources :posts do 
    resources :comments, only: [:new, :edit]
  end 

  resources :comments, only: [:create, :update, :destroy]
  
  resources :likes, only: [:create, :destroy]

  resources :friend_reqs, only: [:create, :show] do
    member do
      post 'accept'
      delete 'reject'
    end
  end
      
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user 
    
    has_many :comments, as: :commentable, dependent: :destroy
    
    has_many :likes, as: :likable, dependent: :destroy

    mount_uploaders :images, ImagesUploader

    validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @post = Post.new
    if current_user
      @rec_users = User.where.not(id: current_user.id)
      @posts = Post.where('user_id IN (?)', current_user.friend_ids).or(Post.where(user_id: current_user.id))
      
      @random_posts = []
      if @posts.length > 6
        6.times do 
          @random_posts << @posts[rand(@posts.length)]
        end
      else 
        @random_posts = @posts
      end
      @random_users = []
      3.times do 
        @random_users << @rec_users[rand(@rec_users.length)]
      end
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = "You have created a post"
      redirect_back fallback_location:root_path
    else 
      render :new, status: :unprocessable_entity  
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      # redirect_back fallback_location: @post
      redirect_to post_path(@post)
    else 
      render :edit, status: :unprocessable_entity    
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "You have deleted a post."
    redirect_to current_user
  end

  private
  def post_params
    params.require(:post).permit(:content,  {images: []})
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_feed.html.erb
<%= 'No posts available to show!' if @random_posts[0].nil? %>
<% @random_posts.each do |p|%>
    <%if !p.nil?%>
    <div class="p-2 border border-dark" >
        <h4><%= link_to p.user.name, p.user%> </h4>
        <%=image_tag(p.user.avatar_url) if p.user.avatar? %>
        <%= p.content%>
        <ul>
        <div>
        <% p.images.each do |i|%>

        <%= image_tag(i.url)%>
        <%end%>
        </div>
        <%="#{p.likes.count} Likes"%>
            <%like = p.likes.where(user_id: current_user.id).first%>
            <%if like.nil?%>
            <%= button_to 'Like', likes_path, params: {like: {user_id: current_user.id, likable_id: p.id, likable_type: 'Post'}}%>
            <%else%> 
            <%=button_to 'Like', like_url(id_like: like.id, id: current_user.id), method: :delete %>
            <%end%>
        </ul>

        <%if p.user == current_user%>
        <ul>
        <%= link_to "Edit", edit_post_path(p), class:"btn btn-outline-primary" %>
        <span>
        <%=button_to 'Delete', post_url(id: p.id), method: :delete, class: "btn btn-secondary"%>
        </ul>
        <%end%>
        <%="#{p.comments.count} Comments"%> 
            <%p.comments.each do |com|%>
            <%=render 'comments/comments', comment: com, id: com.user.id%>
            <%end%>
        <br>
        <h5>Add a comment:</h5>
        <%=render 'comments/form', {type: "Post", id: p.id}%>
    </div>
    <br>
    <%end%>
<%end%>

app/views/posts/_form.html.erb
<div class = "justify-content-center">
<%= form_for @post do |form| %>
    <div>
        <%= form.label :content %><br>
        <%= form.text_area :content, placeholder: "Share your thoughts" %><br>
    </div>
    <div>
        <%= form.file_field :images, multiple:true %><br>
    </div>

    <div class = "align-items-end">
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>

    <div>
        <%= form.submit 'Post'%>
    </div>
    
<% end %>
</div>

app/views/posts/_friendreq.html.erb
<% @random_users.each do |u|%>
        <h6><%=link_to u.name, u%></h6>
        <%current_req = FriendReq.where(from_user_id: current_user.id, to_user_id: u.id)%>
        <%if current_req == [] && !current_user.friends.include?(u)%>
            <%=button_to 'Add friend', {controller: 'friend_reqs', action: 'create', id: u.id}, class: "btn btn-secondary" %>
        <%else%>
            <%='You have already added this friend.'%>
        <%end%>
 
<%end%>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%=render "form", method: :patch%>

app/views/posts/index.html.erb
<div class = "container d-flex justify-content-between">
    <% if user_signed_in? %>
    <div> 
    <br>
    </div>
    <div class="main-container w-75 p-2" > 
        <%=image_tag(current_user.avatar_url) if current_user.avatar? %>
        <div class="align-item-center">
            <%=render 'form' %>
        </div>
        
        <%=render 'feed' %>
      
    </div>
    <div class = "ml-auto p-2">
        <%= render 'friendreq'%>
    </div>
    <%else%>
        <h2 class = "main-container"> Welcome to Connect! </h2>
    <%end%>
</div>

app/views/posts/show.html.erb
<div class="p-2 border border-dark">
        <%=image_tag(@post.user.avatar_url) if @post.user.avatar? %>
        <h6> <%=link_to @post.user.name, @post.user%></h6>
        <%=@post.content%>
        <ul>
        <%=@post.likes.count%>
        <%='Likes'%>    

        <%like = @post.likes.where(user_id: current_user.id)%>
        <%if like == []%>
        <%= button_to 'Like', likes_path, params: {like: {user_id: current_user.id, likable_id: @post.id, likable_type: 'Post'}}%>
        <%else%> 
         <%=button_to 'Like', like_url(id_like: like.id, id: @post.user.id), method: :delete %>
        <%end%>
        </ul>
        <ul>
        <li><%= link_to "Edit", edit_post_path(@post), class:"btn btn-outline-primary" %></li>
       
        <li> <%=button_to 'Delete', post_url(id: @post.id), method: :delete, class: "btn btn-secondary"%></li>
        </ul>
            <%=@post.comments.count%> 
            <%="Comments"%> 
            <%@post.comments.each do |com|%>
            <%=render 'comments/comments', comment: com%>
            <%end%>
        <h6>Add a comment:</h6>
        <%=render 'comments/form', {type: @type_post, id: @post.id}%>
    </div>