config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  post 'posts/index'
  get 'users/index'
  get '/search', to: 'users#search'
  
  
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/auth/:provider/callback' => 'users/sessions#create'
    # get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "posts#index"

  resources :users do
    post 'remove_avatar'
  end

  resources :posts do 
    resources :comments, only: [:new, :edit]
  end 

  resources :comments, only: [:create, :update, :destroy]
  
  resources :likes, only: [:create, :destroy]

  resources :friend_reqs, only: [:create, :show] do
    member do
      post 'accept'
      delete 'reject'
    end
  end
      
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Connect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
<nav class="navbar navbar-expand-md navbar-dark bg-secondary">
  <li class="nav-item active text-white">
    <%= link_to 'Connect', root_path, class: 'text-white navbarColor01'%>
  </li>
  <br>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">  
      <%= form_with url: '/search', method: :get do |form| %>
      <%= form.text_field :key, placeholder: "Enter user's name" %>
      <%= form.submit "Search" %> 
    <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Hi, #{current_user.name}", edit_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "My Profile", current_user, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Friend Request', friend_req_path(current_user), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
    <% flash.each do |type, msg| %>
        <div class="alert alert-info">
            <%= msg %>
        </div>
    <%end%>
    <div class="container">
    <%= yield %>
    </div>
 
  </body>
</html>